apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service-frontend.yaml
  - deployment-frontend.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - default.conf

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-pull-policy.yaml

images:
  - name: sse-cloud-service_coursebot
    newName: sse-cloud-service_coursebot
    newTag: latest
