apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursebot
spec:
  selector:
    matchLabels:
      app: coursebot
  template:
    spec:
      containers:
        - name: coursebot
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-ingestor
spec:
  selector:
    matchLabels:
      app: cb-ingestor
  template:
    spec:
      containers:
        - name: cb-ingestor
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-retriever
spec:
  selector:
    matchLabels:
      app: cb-retriever
  template:
    spec:
      containers:
        - name: cb-retriever
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
