apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services.yaml
  - configmap-ollama-scripts.yaml
  - statefulset-ollama-chat.yaml
  - statefulset-ollama-embed.yaml
  - statefulset-chroma.yaml
  - statefulset-redis.yaml
  - deployment-coursebot.yaml
  - deployment-ingestor.yaml
  - deployment-retriever.yaml
  - deployment-gateway.yaml
