apiVersion: v1
kind: Service
metadata:
  name: coursebot
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: coursebot
---
apiVersion: v1
kind: Service
metadata:
  name: cb-ollama
spec:
  ports:
    - port: 11434
      targetPort: 11434
  selector:
    app: cb-ollama
---
apiVersion: v1
kind: Service
metadata:
  name: cb-chroma
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: cb-chroma
---
apiVersion: v1
kind: Service
metadata:
  name: cb-ingestor
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: cb-ingestor
---
apiVersion: v1
kind: Service
metadata:
  name: cb-retriever
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: cb-retriever
---
apiVersion: v1
kind: Service
metadata:
  name: cb-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: cb-redis
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx-gateway
