apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cb-redis
spec:
  serviceName: cb-redis
  replicas: 1
  selector:
    matchLabels:
      app: cb-redis
  template:
    metadata:
      labels:
        app: cb-redis
    spec:
      containers:
        - name: cb-redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
