apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: nginx-config
    files:
      - default.conf
  - name: dev-guide-config
    files:
      - dev-guide.html

secretGenerator:
  - name: cb-secrets
    envs:
      - .env

# Let configmap changes trigger pod restarts
generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-coursebot.yaml
  - path: patch-ingestor.yaml
  - path: patch-retriever.yaml
  - path: patch-pull-policy.yaml
